### ISSUE TITLE
Example 1 problem

### ISSUE THREAD

**Issue by nataliesilmon** [daler/metaseq#18]
Hi, I am trying to follow example 1 for metaseq (https://daler.github.io/metaseq/example_session.html) and am having problems with the example data. 

I'm following the script by copying from the example page (or the jupyter example page) - it will not generate an example.features file (though the example.npz file is generated). Can you please help me?

code:
metaseq.persistence.save_features_and_arrays(
    features=tsses,
    arrays={'ip': ip_array, 'input': input_array},
    prefix='example',
    link_features=True,
    overwrite=True)

output:
ln: example.features: No such file or directory

**Comment by daler** [comment]
That function, when `link_features=True` (as in this example), will create a symlink rather than copy the data. What happens when you use `link_features=False`?

**Comment by nataliesilmon** [comment]
I don't see the no such file or directory error, but still when I move on to the next section I get an error and can't proceed:

code:

features, arrays = metaseq.persistence.load_features_and_arrays(prefix='example')

output:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Natalie/miniconda/envs/metaseq-test/lib/python2.7/site-packages/metaseq/persistence.py", line 24, in load_features_and_arrays
    features = pybedtools.BedTool(prefix + '.features')
  File "/Users/Natalie/miniconda/envs/metaseq-test/lib/python2.7/site-packages/pybedtools/bedtool.py", line 450, in __init__
    raise ValueError('File "%s" does not exist' % fn)
ValueError: File "example.features" does not exist

**Comment by daler** [comment]
I'm unable to reproduce this. Things to check: Does `tsses-1kb.gtf` exist as created in the previous step(s)? How about `tsses.gtf`? Can you try restarting the session in a different directory? Are there any permission issues in the working directory?
