### ISSUE TITLE
Example1 problem #2

### ISSUE THREAD

**Issue by Fiona-and-Cake** [daler/metaseq#35]
Why do I get an AttributeError when I try to create an array in example 1?

>>> import multiprocessing
>>> processes = multiprocessing.cpu_count()
>>> 
>>> if not os.path.exists('example.npz'):
...     ip_array = ip_signal.array(             
...             tsses_1kb,
...             bins=100,
...             processes=processes)
...     input_array = input_signal.array(
...             tsses_1kb,
...             bins=100,
...             processes=processes)
...     ip_array /= ip_signal.mapped_read_count() / 1e6
...     input_array /= input_signal.mapped_read_count() / 1e6
...     metaseq.persistence.save_features_and_arrays(
...             features=tsses,
...             arrays={'ip':ip_array, 'input':input_array},
...             prefix='example',
...             link_features=True,
...             overwrite=True)
... 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 122, in array
    chunksize=chunksize, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/array_helpers.py", line 383, in _array_parallel
    itertools.repeat(kwargs)))
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'group'

Thanks!

**Comment by daler** [comment]
Thanks for reporting. Unfortunately, I'm unable to reproduce the issue. For troubleshooting, can you please try setting `processes = 1` and then re-run to get a more informative error message.

**Comment by Fiona-and-Cake** [comment]
>>> import multiprocessing
>>> processes = multiprocessing.cpu_count()
>>> 
>>> if not os.path.exists('example.npz'):
...             ip_array = ip_signal.array(             
...                     tsses_1kb,
...                     bins=100,
...                     processes=processes)
...             input_array = input_signal.array(
...                     tsses_1kb,
...                     bins=100,
...                     processes=1)
...             ip_array /= ip_signal.mapped_read_count() / 1e6
...             input_array /= input_signal.mapped_read_count() / 1e6
...             metaseq.persistence.save_features_and_arrays(
...                     features=tsses,
...                     arrays={'ip':ip_array, 'input':input_array},
...                     prefix='example',
...                     link_features=True,
...                     overwrite=True)
... 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 122, in array
    chunksize=chunksize, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/array_helpers.py", line 383, in _array_parallel
    itertools.repeat(kwargs)))
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'group'


It gives me the same error as before. I've also tried with processes = None

**Comment by daler** [comment]
There are multiple calls in that chunk, and it looks like you only changed the second one.

How about just running this:

```python
 ip_array = ip_signal.array(
    tsses_1kb,
    bins=100,
    processes=1)
```

**Comment by Fiona-and-Cake** [comment]
Whoops! Good point. Same thing happens with just one though.

>>> ip_array = ip_signal.array(             
...             tsses_1kb,
...             bins=100,
...             processes=1)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 122, in array
    chunksize=chunksize, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/array_helpers.py", line 383, in _array_parallel
    itertools.repeat(kwargs)))
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/nakadalab/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by daler** [comment]
Can you try the same with `processes=None` please?

**Comment by Fiona-and-Cake** [comment]
>>> if not os.path.exists('example.npz'):
...             ip_array = ip_signal.array(             
...                     tsses_1kb,
...                     bins=100,
...                     processes=None)
... 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 124, in array
    arrays = _array(self.fn, self.__class__, features, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/array_helpers.py", line 415, in _array
    reader, gene, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 135, in local_coverage
    return _local_coverage(self.adapter, features, *args, **kwargs)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/array_helpers.py", line 244, in _local_coverage
    window = helpers.tointerval(window)
  File "/Users/nakadalab/miniconda/lib/python2.7/site-packages/metaseq/helpers.py", line 99, in tointerval
    if m.group('strand'):
AttributeError: 'NoneType' object has no attribute 'group'

Slightly different, but the same AttributeError.

**Comment by daler** [comment]
Something strange is happening in `tsses_1kb`. Can you try regenerating it and trying again? If it's still giving the same error, what are the results of:

```python
type(tsses_1kb)
tsses_1kb.head()
```
or, from the terminal,

```bash
head tsses.gtf
```

**Comment by Fiona-and-Cake** [comment]
Regenerating it seems to have worked! Thank you so much :) I'm still not entirely sure what went wrong the first time I made the tsses_1kb file though.
